export const indemnityBondTemplate = (data) => {
  // 1. Dynamic Grammar Logic
  const isSellerPlural = data.sellers && data.sellers.length > 1;
  const isPurchaserPlural = data.purchasers && data.purchasers.length > 1;

  // Seller Grammar
  const s_PronounSubj = isSellerPlural ? "We" : "I";
  const s_VerbBe = isSellerPlural ? "are" : "am";
  const s_PronounPoss = isSellerPlural ? "our" : "my";
  const s_Transferor = isSellerPlural ? "Transferors" : "Transferor";
  const s_Seller = isSellerPlural ? "Sellers" : "Seller";
  const s_Deponent = isSellerPlural ? "Deponents" : "Deponent";

  // Purchaser Grammar
  const p_Noun = isPurchaserPlural ? "purchasers" : "purchaser";
  const p_Transferee = isPurchaserPlural ? "Transferees" : "Transferee";

  // 2. Helper Function for Detailed Seller Formatting
  const formatSellerDetails = (sellers, address) => {
    if (!sellers || sellers.length === 0) return "";

    const details = sellers.map(
      (s) =>
        `<strong>${s.title} ${s.name}</strong>, aged ${s.age || "___"} years, having (PAN NO. <strong>${s.pan || "__________"}</strong>)`,
    );

    let formattedSellers = "";
    if (details.length === 1) {
      formattedSellers = details[0];
    } else if (details.length === 2) {
      formattedSellers = details.join(" & ");
    } else {
      formattedSellers =
        details.slice(0, -1).join(", ") + " & " + details[details.length - 1];
    }

    let inhabitantGrammar = "";
    if (sellers.length === 1) {
      inhabitantGrammar = "an adult, Indian inhabitant";
    } else if (sellers.length === 2) {
      inhabitantGrammar = "both adult, Indian inhabitants";
    } else {
      inhabitantGrammar = "all adult, Indian inhabitants";
    }

    const finalAddress = address
      ? `Resident at ${address}`
      : "Resident at ________________________";
    const residentGrammar = isSellerPlural ? "Residents" : "Resident";

    return `${formattedSellers}, ${inhabitantGrammar}, ${residentGrammar} ${finalAddress}`;
  };

  // 3. Extract pre-formatted names generated by the React form
  const purchaserNames = data.purchaserNames || "______________________";
  const sellerNames = data.sellerNames || "______________________";

  // 4. Fallback for Property Address
  const fullPropertyAddress =
    data.propertyAddress ||
    `Flat No. ${data.flatNo || "____"}, ${data.buildingAddress || "____"}, ${data.societyName || "____"}`;

  // 5. The Template Literal (Exact Formatting & Alignment)
  return `
    <div style="font-family: 'Times New Roman', Times, serif; font-size: 11pt; line-height: 1.8; max-width: 850px; margin: 0 auto; text-align: justify; color: #000; padding: 40px;">
        
        <h2 style="text-align: center; text-decoration: underline; font-weight: bold; font-size: 14pt; margin-bottom: 30px;">
            INDEMNITY BOND
        </h2>

        <p style="margin-bottom: 20px; ">
            THIS INDENTURE OF INDEMNITY BOND is executed, <strong>${data.placeOfExecution || "Navi Mumbai"}</strong> on this ___day of __________, 20___.
        </p>

        <p style="margin-bottom: 20px;">
            ${formatSellerDetails(data.sellers, data.sellerAddress)}, in favour of <strong>CITY AND INDUSTRIAL DEVELOPMENT CORPORATION OF MAHARASHTRA LTD.</strong> (hereinafter for the sake of brevity referred as <strong>THE CORPORATION</strong>)
        </p>

        <p style="margin-bottom: 20px;">
            <strong>WHEREAS:</strong> ${s_PronounSubj} ${s_VerbBe} seized and possessed <strong>${fullPropertyAddress}</strong> (hereinafter referred to as the said Premises). (hereinafter for the sake of brevity referred to as The said premises)
        </p>

        <p style="margin-bottom: 20px;">
            <strong>AND WHEREAS</strong> ${s_PronounSubj} ${s_VerbBe} desirous of transferring the said premises, in favour of the intending ${p_Transferee}, <strong>${purchaserNames}</strong>, (hereinafter for the sake of brevity referred to as The said ${p_Noun})
        </p>

        <p style="margin-bottom: 20px;">
            <strong>AND WHEREAS</strong> ${s_PronounSubj} have not mortgaged/ sold/ the above said premises to anybody except <strong>${purchaserNames}</strong>
        </p>

        <p style="margin-bottom: 30px;">
            <strong>AND WHEREAS</strong> with a view to safeguard the interest of the Corporation against any contingent claim by any person, ${s_PronounSubj} hereby execute this Indemnity Bond in favour of the said Corporation.
        </p>

        <p style="text-align: center; font-weight: bold; font-size: 12pt; margin-top: 40px; margin-bottom: 30px; letter-spacing: 0.5px;">
            NOW THIS BOND OF INDEMNITY WITNESSES AS FOLLOWS
        </p>

        <p style="margin-bottom: 20px;">
           1). In consideration of the said premises and in pursuance of the said Corporation having agreed to transfer the said premises in the name of the said ${p_Noun}, ${s_PronounPoss} heirs, executors, administration shall at all time hereinafter remain liable for and shall fully and effectually indemnity and keep indemnified the said Corporation, its successors and assignees against all losses and damages, costs, and expenses, claims, penalties or any other action Whatsoever Which may be put to or may be incurred or suffered by reason of the transfer of the said premises in the name of said ${p_Noun} by the said Corporation.
        </p>

        <p style="margin-bottom: 20px;">
          2). ${s_PronounSubj} hereby indemnity the said Corporation and undertake to keep the Corporation harmless.
        </p>

        <p style="margin-bottom: 20px;">
         3). ${s_PronounSubj} hereby further state that in case any person succeeds in imposing any penalty or any other dues on the said Corporation, ${s_PronounSubj} shall make good any loss that may be sustained by the said Corporation by the transferring the said premises in the name of said ${p_Noun}.
        </p>

        <p style="margin-bottom: 40px;">
            In <strong>WITNESS WHEREOF</strong> ${s_PronounSubj} have set and subscribed ${s_PronounPoss} hands to this bond of indemnity on this _____ day of _______________, 20___.
        </p>

        <div style="display: flex; justify-content: flex-end; margin-top: 60px;">
            <div style="text-align: center; min-width: 300px;">
                <p style="margin-bottom: 60px;"><strong>${s_Deponent}</strong></p>
                <p>___________________________</p>
                <p style="margin-top: 5px;"><strong>${sellerNames}</strong></p>
            </div>
        </div>

    </div>
  `;
};
